## 역전파 테스트

In [2]:
import os
import sys 
import numpy as np

# 현재 작업 중인 Notebook의 경로 가져오기
notebook_dir = os.getcwd()
sys.path.append(os.path.abspath(os.path.join(notebook_dir, "../class")))

from Layer import Layer

isize=4
hsize=3
osize=2

activation="leaky_relu"

idata=np.array([0.5, 0.3, 0.9, 0.1])

ilayer=Layer(isize,activation,hsize)
ilayer.set_layer(idata)
ilayer.set_weight()

hlayer=Layer(hsize,activation,osize)
hlayer.set_weight()

olayer=Layer(osize,"none")

res_val, res_gradient = ilayer.forward()

# 결과 값을 다음 레이어의 노드들에 할당
for i in range(hlayer.layer_size):
    hlayer.nodes[i].val = res_val[i]
    hlayer.nodes[i].activation_gradient = res_gradient[i]

print(res_val)
print(res_gradient)

res_val, res_gradient = hlayer.forward()

for i in range(olayer.layer_size):
    olayer.nodes[i].val = res_val[i]
    olayer.nodes[i].activation_gradient = res_gradient[i]


print("Forward Pass Output Values:", olayer.nodes[1].val)
print("Forward Pass Output Values:", olayer.nodes[1].activation_gradient)

olayer.get_gradient_output([1,0])
next_layer=[node.val for node in olayer.nodes]
print("next_layer val: ",next_layer)
hlayer.get_gradient(next_layer)
prev_layer=[node.val for node in ilayer.nodes]
hlayer.update_weight(prev_layer)



[ 0.91973792  1.54551661 -0.00165332]
[1.   1.   0.01]
Forward Pass Output Values: 4.42574969
Forward Pass Output Values: 1.0
next_layer val:  [2.35388007, 4.42574969]
------------------------------------
1.5908391520830512
* result :  0.6856709220035435
* :  13.71341844007087   0.5
0.9051682300795076
------------------------------------
2.252448638912264
* result :  0.4114025532021261
* :  13.71341844007087   0.3
1.841046085710138
------------------------------------
0.5746081619690502
* result :  0.40489312138556666
* :  8.097862427711332   0.5
0.16971504058348352
------------------------------------
1.5241042082506597
* result :  0.24293587283134
* :  8.097862427711332   0.3
1.2811683354193197
------------------------------------
-1.6079905358510225
* result :  3.6332489508400005e-05
* :  0.000726649790168   0.5
-1.6080268683405308
------------------------------------
0.8716448340541215
* result :  2.179949370504e-05
* :  0.000726649790168   0.3
0.8716230345604165


In [3]:

res_val, res_gradient = ilayer.forward()

# 결과 값을 다음 레이어의 노드들에 할당
for i in range(hlayer.layer_size):
    hlayer.nodes[i].val = res_val[i]
    hlayer.nodes[i].activation_gradient = res_gradient[i]

print(res_val)
print(res_gradient)

res_val, res_gradient = hlayer.forward()

for i in range(olayer.layer_size):
    olayer.nodes[i].val = res_val[i]
    olayer.nodes[i].activation_gradient = res_gradient[i]


print("Forward Pass Output Values:", olayer.nodes[1].val)
print("Forward Pass Output Values:", olayer.nodes[1].activation_gradient)

olayer.get_gradient_output([1,0])
next_layer=[node.val for node in olayer.nodes]
print("next_layer val: ",next_layer)
hlayer.get_gradient(next_layer)
prev_layer=[node.val for node in ilayer.nodes]
hlayer.update_weight(prev_layer)


[ 0.91973792  1.54551661 -0.00165332]
[1.   1.   0.01]
Forward Pass Output Values: 3.67190577
Forward Pass Output Values: 1.0
next_layer val:  [1.09747354, 3.67190577]
------------------------------------
0.9051682300795076
* result :  0.3876772963357931
* :  7.753545926715862   0.5
0.5174909337437146
------------------------------------
1.841046085710138
* result :  0.23260637780147586
* :  7.753545926715862   0.3
1.608439707908662
------------------------------------
0.16971504058348352
* result :  0.24452935847739476
* :  4.890587169547895   0.5
-0.07481431789391124
------------------------------------
1.2811683354193197
* result :  0.14671761508643685
* :  4.890587169547895   0.3
1.1344507203328829
------------------------------------
-1.6080268683405308
* result :  0.0007178753551272501
* :  0.014357507102545   0.5
-1.6087447436956581
------------------------------------
0.8716230345604165
* result :  0.00043072521307635004
* :  0.014357507102545   0.3
0.8711923093473402
